import 'package:flutter_training/core/constants/app_images_url.dart';
import 'package:flutter_training/core/constants/app_strings.dart';
import 'package:flutter_training/features/dashboard/domain/entity/response/album_items.dart';

class AlbumDataSource {
  static const String _base = AppImagesUrl.placeholderImageBase;
  static const String _cityLogoBase = AppImagesUrl.cityLogoBaseUrl;

  static String _cityLogo(String cityKeyword, String id) =>
      '${_cityLogoBase}80/80/$cityKeyword?lock=$id';

  static List<AlbumItems> get albums => [
    AlbumItems(
      '$_base/id/10/200',
      _cityLogo('karachi', '1'),
      AppStrings.mountainView,
      '1',
      AppStrings.sampleWebsite,
      AppStrings.mountainViewLocation,
      AppStrings.mountainViewDescription,
    ),
    AlbumItems(
      '$_base/id/11/200',
      _cityLogo('lahore', '2'),
      AppStrings.lushForest,
      '2',
      AppStrings.sampleWebsite,
      AppStrings.lushForestLocation,
      AppStrings.lushForestDescription,
    ),
    AlbumItems(
      '$_base/id/12/200',
      _cityLogo('islamabad', '3'),
      AppStrings.oceanWaves,
      '3',
      AppStrings.sampleWebsite,
      AppStrings.oceanWavesLocation,
      AppStrings.oceanWavesDescription,
    ),
    AlbumItems(
      '$_base/id/13/200',
      _cityLogo('peshawar', '4'),
      AppStrings.desertDunes,
      '4',
      AppStrings.sampleWebsite,
      AppStrings.desertDunesLocation,
      AppStrings.desertDunesDescription,
    ),
    AlbumItems(
      '$_base/id/14/200',
      _cityLogo('quetta', '5'),
      AppStrings.cityLights,
      '5',
      AppStrings.sampleWebsite,
      AppStrings.cityLightsLocation,
      AppStrings.cityLightsDescription,
    ),
    AlbumItems(
      '$_base/id/15/200',
      _cityLogo('rawalpindi', '6'),
      AppStrings.autumnLeaves,
      '6',
      AppStrings.sampleWebsite,
      AppStrings.autumnLeavesLocation,
      AppStrings.autumnLeavesDescription,
    ),
    AlbumItems(
      '$_base/id/16/200',
      _cityLogo('sialkot', '7'),
      AppStrings.snowyPeaks,
      '7',
      AppStrings.sampleWebsite,
      AppStrings.snowyPeaksLocation,
      AppStrings.snowyPeaksDescription,
    ),
    AlbumItems(
      '$_base/id/17/200',
      _cityLogo('sukkur', '8'),
      AppStrings.grassyFields,
      '8',
      AppStrings.sampleWebsite,
      AppStrings.grassyFieldsLocation,
      AppStrings.grassyFieldsDescription,
    ),
    AlbumItems(
      '$_base/id/18/200',
      _cityLogo('multan', '9'),
      AppStrings.deepBlue,
      '9',
      AppStrings.sampleWebsite,
      AppStrings.deepBlueLocation,
      AppStrings.deepBlueDescription,
    ),
    AlbumItems(
      '$_base/id/19/200',
      _cityLogo('faisalabad', '10'),
      AppStrings.starryNight,
      '10',
      AppStrings.sampleWebsite,
      AppStrings.starryNightLocation,
      AppStrings.starryNightDescription,
    ),
    AlbumItems(
      '$_base/id/20/200',
      _cityLogo('gujranwala', '11'),
      AppStrings.goldenSunset,
      '11',
      AppStrings.sampleWebsite,
      AppStrings.goldenSunsetLocation,
      AppStrings.goldenSunsetDescription,
    ),
    AlbumItems(
      '$_base/id/21/200',
      _cityLogo('hyderabad', '12'),
      AppStrings.mistyRiver,
      '12',
      AppStrings.sampleWebsite,
      AppStrings.mistyRiverLocation,
      AppStrings.mistyRiverDescription,
    ),
    AlbumItems(
      '$_base/id/22/200',
      _cityLogo('karachi', '13'),
      AppStrings.quietLake,
      '13',
      AppStrings.sampleWebsite,
      AppStrings.quietLakeLocation,
      AppStrings.quietLakeDescription,
    ),
    AlbumItems(
      '$_base/id/23/200',
      _cityLogo('kashmir', '14'),
      AppStrings.canyonRocks,
      '14',
      AppStrings.sampleWebsite,
      AppStrings.canyonRocksLocation,
      AppStrings.canyonRocksDescription,
    ),
    AlbumItems(
      '$_base/id/24/200',
      _cityLogo('lahore', '15'),
      AppStrings.greenValley,
      '15',
      AppStrings.sampleWebsite,
      AppStrings.greenValleyLocation,
      AppStrings.greenValleyDescription,
    ),
    AlbumItems(
      '$_base/id/25/200',
      _cityLogo('lahore', '16'),
      AppStrings.palmBeach,
      '16',
      AppStrings.sampleWebsite,
      AppStrings.palmBeachLocation,
      AppStrings.palmBeachDescription,
    ),
  ];
}
